apiVersion: apps/v1
kind: Deployment
metadata:
 name: gke-devops
 labels:
   app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: southamerica-east1-docker.pkg.dev/devops-405416/devops-repository/python-app:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: python-app
spec:
  type: NodePort
  selector:
    run: web
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "devops"
  labels:
    app: python-app
spec:
  defaultBackend:
    service:
      name: web
      port:
        number: 8000