apiVersion: apps/v1
kind: Deployment
metadata:
 name: gke-devops
 labels:
   app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: southamerica-east1-docker.pkg.dev/devops-405416/devops-repository/python-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gke-lb
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - port: 8000
      targetPort: 8000