apiVersion: apps/v1
kind: Deployment
metadata:
 name: gke-devops
 labels:
   app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/python-app:$GITHUB_SHA
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: python-app